ADMIN_IDS = [123, ]
BASE_URL = "https://domain"
MAIN_BOT_TOKEN = "bot:token"
MAIN_BOT_PATH = "/webhook/main"

OTHER_BOTS_PATH = "/webhook/bot/{bot_token}"
OTHER_BOTS_URL = f"{BASE_URL}{OTHER_BOTS_PATH}"

WEB_SERVER_HOST = "127.0.0.1"
WEB_SERVER_PORT = 8081


MAIN_POSTGRES_HOST = "localhost"
MAIN_POSTGRES_PORT = 5432
MAIN_POSTGRES_USER = 'eugen'
MAIN_POSTGRES_PASS = '12weather_eugen_app34'
MAIN_POSTGRES_DB = 'testing'
MAIN_POSTGRES_URI = f"postgresql://{MAIN_POSTGRES_USER}:{MAIN_POSTGRES_PASS}@{MAIN_POSTGRES_HOST}:{MAIN_POSTGRES_PORT}" \
                    f"/{MAIN_POSTGRES_DB}"

CHILD_POSTGRES_HOST = "localhost"
CHILD_POSTGRES_PORT = 5432
CHILD_POSTGRES_USER = 'eugen'
CHILD_POSTGRES_PASS = '12weather_eugen_app34'
CHILD_POSTGRES_DB = 'testing'
CHILD_POSTGRES_URI = f"postgresql://{CHILD_POSTGRES_USER}:{CHILD_POSTGRES_PASS}@{CHILD_POSTGRES_HOST}" \
                     f":{CHILD_POSTGRES_PORT}/{CHILD_POSTGRES_DB}"


REDIS_DSN = "redis://127.0.0.1:6479"


